package web

import org.gradle.kotlin.dsl.application
import org.gradle.kotlin.dsl.dependencies

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("spring-common-conventions")
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}