/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
import org.springframework.context.annotation.ComponentScan

@SpringBootApplication
@ComponentScan("org.example")
open class App

fun main(args: Array<String>) {
    runApplication<App>(*args)
}