/*
 * This file was generated by the Gradle 'init' task.
 */

group = "dev.luciano"
version = "1.0.0"

plugins {
    id("spring-common-conventions")
    id("web.spring-reactive-web-conventions")
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter")
    implementation(project(":reactive-web"))
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.AppKt"
}
